### ISSUE TITLE
`docker-compose up` is not turnkey on Windows hosts

### ISSUE THREAD

**Issue by ChrisRimmer** [prometheus-community/prometheus-playground#10]
Seems to be due to bdc046a4 - the image tag variables in the docker-compose files rely on the makefile executing to populate them. Windows users don't have Make, so they're running `docker-compose up` directly, so the vars don't load. `docker-compose` falls back to using empty strings, resulting in an `invalid reference format` error as they're trying to pull `prom/prometheus:` for example.

I'm not sure if you'd rather use `.env` files to apply default tag values rather than store them in a an include in the makefile, or revert the change, or just ignore Windows users.

**Comment by lucperkins** [comment]
@ChrisRimmer The advantage of the current solution is that the environment variables are all set in one place but if it's not turnkey for Windows then it needs to be re-thought (I'm too often guilty of Windows neglect...mea culpa!). I can fix this quickly.

**Comment by lucperkins** [comment]
@ChrisRimmer AFAICT this is fixed after the merge of #11. If you continue to have issues please let me know and I'll address as soon as I can! Thanks for pointing this out 👍 I will try to be more mindful of Windows folx in the future.

**Comment by ChrisRimmer** [comment]
Thanks - it's nice to see a break from some of the normal Windows hate :) I readily admit we're easy to forget about!
